<?php
/**
 * Copyright © 2017 Ptaang, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Ptaang\Seller\Block\Collection\ListProducts $block */
?>

<?php
$products = $block->getProducts();
$sellerId = $block->getSellerId();
?>
<?php if(count($products) > 0): ?>
    <div class="table-wrapper seller-product">
        <table class="data table table-seller-items" id="my-seller-products">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('My Products') ?></caption>
            <thead>
                <th scope="col" class="col name"><?php /* @escapeNotVerified */ echo __('Name') ?></th>
                <th scope="col" class="col sku"><?php /* @escapeNotVerified */ echo __('Sku') ?></th>
                <th scope="col" class="col qty"><?php /* @escapeNotVerified */ echo __('Qty') ?></th>
                <th scope="col" class="col qty-sold"><?php /* @escapeNotVerified */ echo __('Qty sold') ?></th>
                <th scope="col" class="col action"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
            </thead>
            <tbody>
                <?php foreach ($products as $product): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Name')) ?>" class="col name">
                            <?php /* @escapeNotVerified */ echo $product->getName() ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Sku')) ?>" class="col sku">
                            <?php /* @escapeNotVerified */ echo $product->getSku() ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Qty')) ?>" class="col qty">
                            <?php /* @escapeNotVerified */ echo $block->getQty($product); ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Qty sold')) ?>" class="col qty-sold">
                            <?php /* @escapeNotVerified */ echo $block->getQtySold($product->getId(), $sellerId) ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Action')) ?>" class="col action">
                            <a href="<?php echo $product->getProductUrl(); ?>">
                                <?php /* @escapeNotVerified */ echo __("Show"); ?>
                            </a> /
                            <a href="<?php echo $block->getEditProductUrl($product->getId()); ?>">
                                <?php /* @escapeNotVerified */ echo __("Edit"); ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="table-wrapper seller-product">
        <p><?php /* @escapeNotVerified */ echo __('You have no products created') ?></p>
    </div>
<?php endif; ?>
