
<div class="field field-name required">
    <label class="label" for="name"><?php /* @escapeNotVerified */ echo __("Name"); ?></label>
    <div class="control">
        <input id="name" name="name" class="input-text required-entry" type="text">
    </div>
</div>

<div class="field field-price required">
    <label class="label" for="price"><?php /* @escapeNotVerified */ echo __("Price"); ?></label>
    <div class="control">
        <input id="price" name="price" class="input-text required-entry" type="text">
    </div>
</div>

<div class="field field-status required">
    <label class="label" for="status"><?php /* @escapeNotVerified */ echo __("Status"); ?></label>
    <div class="control">
        <select id="status" name="status" class="required-entry">
            <option value="0"><?php /* @escapeNotVerified */ echo __("Disabled"); ?></option>
            <option value="1"><?php /* @escapeNotVerified */ echo __("Enabled"); ?></option>
        </select>
    </div>
</div>

<div class="field field-qty required">
    <label class="label" for="qty"><?php /* @escapeNotVerified */ echo __("Quantity"); ?></label>
    <div class="control">
        <input id="qty" name="extension_attributes[qty]" class="input-text required-entry" type="text" data-validate="{'validate-number':true}">
    </div>
</div>

<div class="field field-description required">
    <label class="label" for="description"><?php /* @escapeNotVerified */ echo __("Description"); ?></label>
    <div class="control">
        <textarea id="description" name="custom_attributes[description]" class="textarea required-entry"  ></textarea>
    </div>
</div>

<div class="field field-short_description">
    <label class="label" for="short_description"><?php /* @escapeNotVerified */ echo __("Short Description"); ?></label>
    <div class="control">
        <textarea id="short_description" name="custom_attributes[short_description]" class="textarea"  ></textarea>
    </div>
</div>