<div class="field field-name required">
    <label class="label" for="name"><?php /* @escapeNotVerified */ echo __("Name"); ?></label>
    <div class="control">
        <input id="name" name="name" class="input-text required-entry" type="text">
    </div>
</div>
<div class="field field-sku required">
    <label class="label" for="sku"><?php /* @escapeNotVerified */ echo __("Sku"); ?></label>
    <div class="control">
        <input id="sku" name="sku" class="input-text required-entry" type="text">
    </div>
</div>
<div class="field field-price required">
    <label class="label" for="price"><?php /* @escapeNotVerified */ echo __("Price"); ?></label>
    <div class="control">
        <input id="price" name="price" class="input-text required-entry" type="text">
    </div>
</div>
<div class="field field-quantity required">
    <label class="label" for="quantity"><?php /* @escapeNotVerified */ echo __("Quantity"); ?></label>
    <div class="control">
        <input id="quantity" name="quantity" class="input-text required-entry" type="text">
    </div>
</div>