<?php
/**
 * Copyright © 2017 Ptaang, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Ptaang\Seller\Block\Form\Fieldset\Image $block */
?>
<fieldset id="fieldset-images" class="fieldset images" data-bind="scope:'images'">
    <legend class="legend"><?php /* @escapeNotVerified */ echo __("Product Images"); ?></legend>
    <div class="field">
        <label class="label" ><?php /* @escapeNotVerified */ echo __("Choose your image"); ?></label>
        <div class="control">
            <input type="file" multiple data-bind="event:{change: fileSelect}" accept="image/*">
        </div>
    </div>
    <div>
    <ul data-bind="foreach: { data: newProduct.imagesFile, as: 'imagesFile' }" class="image-gallery">
       <!-- ko foreach: $parent.getRegion('imageItem') -->
                <!-- ko template: {name: getTemplate(), data: imagesFile} --><!-- /ko -->
       <!-- /ko -->
    </ul>
    </div>
    <script type="text/x-magento-init">
           {
               "#fieldset-images": {
                   "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
               }
           }
    </script>
</fieldset>