<?php
/**
 * Copyright © 2017 Ptaang, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Ptaang\Seller\Block\Form\NewProduct $block */
$product =  null;
if($block->isEditingTheProduct()){
    $product = $block->getProduct();
}
?>
<div id="new-product-form" class="new-product-form" data-bind="scope:'sellernewproduct'">
    <div class="block-manage-products add-new-products">
        <div class="form-block">
            <form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('seller/account/productPost') ?>"
                  method="post" id="form-validate" enctype="multipart/form-data"
                  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                  data-bind="submit:createProduct, blockLoader: newProduct.formLoader">
                <fieldset class="fieldset info" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                    <legend class="legend">
                        <?php /* @escapeNotVerified */ echo __("Product information"); ?>
                    </legend>
                    <?php if(!$block->isEditingTheProduct()):?>
                        <div class="field field-type required">
                            <label class="label" for="type"><?php /* @escapeNotVerified */ echo __("Choose the type of Product"); ?></label>
                            <div class="control">
                                <select id="type" class="required-entry" name="attribute_set_id" data-bind="options: newProduct.productTypes,
                                                                                    optionsText: 'name',
                                                                                    optionsValue: 'id',
                                                                                    optionsCaption: $t('Choose your type Product...'),
                                                                                    value: newProduct.selectedProductType,
                                                                                    event:{ change: selectProductType}"></select>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="field field-category required">
                        <label class="label" for="category"><?php /* @escapeNotVerified */ echo __("Categories"); ?></label>
                        <div class="control">
                            <input id="category" name="custom_attributes[category_ids]" class="input-text required-entry" type="text" readonly="readonly"
                                   data-bind="click: showCategoryList, value: newProduct.categorySelected">
                            <ul class="category-list" data-bind="foreach: { data: newProduct.categoryList, as: 'category' },
                                                                                visible: newProduct.showCategoryList">
                                <!-- ko foreach: $parent.getRegion('category') -->
                                    <!-- ko template: {name: getTemplate(), data: category} --><!-- /ko -->
                                <!-- /ko -->
                            </ul>
                        </div>
                    </div>
                    <div class="field field-sku required" data-bind="blockLoader: newProduct.skuLoader">
                        <label class="label" for="sku"><?php /* @escapeNotVerified */ echo __("Sku"); ?></label>
                        <div class="control">
                            <input id="sku" name="sku" class="input-text required-entry" type="text"
                                   <?php if($block->isEditingTheProduct() && $product !== null): ?>
                                       readonly="readonly"
                                       value="<?php echo $product->getSku(); ?>"
                                   <?php else: ?>
                                       data-bind="value: newProduct.skuValue,
                                              valueUpdate: 'afterkeydown',
                                              event: { change: searchSku}"
                                   <?php endif; ?>
                             />
                        </div>
                        <div class="message warning" data-bind="visible: newProduct.showSkuWarning" style="display: none">
                            <span data-bind="text: newProduct.skuWarning"></span>
                        </div>
                    </div>
                    <div class="field field-name required">
                        <label class="label" for="name"><?php /* @escapeNotVerified */ echo __("Name"); ?></label>
                        <div class="control">
                            <input id="name" name="name" class="input-text required-entry" type="text"
                                   value="<?php echo ($block->isEditingTheProduct() && $product !== null)?  $product->getName(): ""; ?>">
                        </div>
                    </div>

                    <div class="field field-price required">
                        <label class="label" for="price"><?php /* @escapeNotVerified */ echo __("Price"); ?></label>
                        <div class="control">
                            <input id="price" name="price" class="input-text required-entry" type="text"
                                   data-validate="{required:true, 'validate-price':true}"
                                   value="<?php echo ($block->isEditingTheProduct() && $product !== null)?
                                       number_format($product->getPriceInfo()->getPrice('final_price')->getValue(), 2) : 0.00; ?>"
                            />
                            <span class="note"><?php echo __("Add a price with 2 decimals for example: 12.00 or 12.50"); ?></span>
                        </div>
                    </div>

                    <div class="field field-status required">
                        <label class="label" for="status"><?php /* @escapeNotVerified */ echo __("Status"); ?></label>
                        <div class="control">
                            <?php $stockStatus = ($block->isEditingTheProduct() && $product !== null) ? $product->getStatus(): 0; ?>
                            <select id="status" name="status" class="required-entry">
                                <option value="0" <?php if($stockStatus == 0): ?>selected<?php endif;?>><?php /* @escapeNotVerified */ echo __("Disabled"); ?></option>
                                <option value="1" <?php if($stockStatus == 1): ?>selected<?php endif;?>><?php /* @escapeNotVerified */ echo __("Enabled"); ?></option>
                            </select>
                        </div>
                    </div>

                    <div class="field field-qty required">
                        <label class="label" for="qty"><?php /* @escapeNotVerified */ echo __("Quantity"); ?></label>
                        <div class="control">
                            <input id="qty" name="extension_attributes[qty]" class="input-text required-entry" type="text" data-validate="{'validate-number':true}"
                                   value="<?php echo ($block->isEditingTheProduct() && $product !== null)?  $block->getStockProduct($product->getId()) : 100; ?>" />

                        </div>
                    </div>

                    <div class="field field-description required">
                        <label class="label" for="description"><?php /* @escapeNotVerified */ echo __("Description"); ?></label>
                        <div class="control">
                            <textarea id="description" name="custom_attributes[description]" class="textarea required-entry"  >
                                <?php echo ($block->isEditingTheProduct() && $product !== null)?  $product->getDescription(): ""; ?>
                            </textarea>

                        </div>
                    </div>

                    <div class="field field-short_description">
                        <label class="label" for="short_description"><?php /* @escapeNotVerified */ echo __("Short Description"); ?></label>
                        <div class="control">
                            <textarea id="short_description" name="custom_attributes[short_description]" class="textarea"  >
                                <?php echo ($block->isEditingTheProduct() && $product !== null)?  $product->getShortDescription(): ""; ?>
                            </textarea>
                        </div>
                    </div>


                </fieldset>
                <?php echo $this->getChildHtml('form_image') ?>

                <?php if($block->isEditingTheProduct() && $product !== null): ?>
                    <?php $customAttributes = $block->getCustomAttributes($product->getAttributeSetId()); ?>
                    <?php if(count($customAttributes) > 0 ): ?>
                        <fieldset class="fieldset extra-info">
                            <legend class="legend">
                                <?php /* @escapeNotVerified */ echo __("Product extra information"); ?>
                            </legend>
                            <?php foreach ($customAttributes as $customAttribute): ?>
                                <?php if($customAttribute["frontend_input"] == "select"): ?>
                                    <div class="field required field-<?php echo $customAttribute["attribute_code"]?>">
                                        <label class="label" for="<?php echo $customAttribute["attribute_code"]; ?>" >
                                            <?php echo $customAttribute["frontend_label"]; ?>
                                        </label>
                                        <?php $attributeValue = $product->getCustomAttribute($customAttribute["attribute_code"])->getValue(); ?>
                                        <div class="control">
                                            <select name="custom_attributes[<?php echo $customAttribute["attribute_code"]; ?>]">
                                                    id="<?php echo $customAttribute["attribute_code"]; ?>"
                                                    class="<?php echo $customAttribute["is_required"]? "required-entry" : ""; ?>"
                                                    <?php foreach ($customAttribute["options"] as $option): ?>
                                                        <option value="<?php echo $option["value"]; ?>" <?php echo $attributeValue == $option["value"]?"selected":""; ?>>
                                                            <?php echo $option["label"]; ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </fieldset>
                    <?php endif; ?>
                <?php else: ?>
                    <fieldset class="fieldset extra-info" data-bind="foreach: { data: newProduct.attributes, as: 'attribute' }">
                        <legend class="legend">
                            <?php /* @escapeNotVerified */ echo __("Product extra information"); ?>
                        </legend>
                        <!-- ko if: (attribute.frontend_input == 'select') -->
                            <!-- ko foreach: $parent.getRegion('attributeSelect') -->
                                <!-- ko template: {name: getTemplate(), data: attribute } --><!-- /ko -->
                            <!-- /ko -->
                        <!-- /ko -->
                    </fieldset>
                <?php endif; ?>


                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action save primary" type="submit" title="Save">
                            <span><?php /* @escapeNotVerified */ echo __("Create Product"); ?></span>
                        </button>
                    </div>
                 </div>
            </form>
        </div>
    </div>
    <script type="text/x-magento-init">
           {
               "#new-product-form": {
                   "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
               }
           }
    </script>
    <script>
        storeCode = '<?php /* @escapeNotVerified */ echo $block->getCurrentWebsiteCode(); ?>';
        token = '<?php /* @escapeNotVerified */ echo $block->getToken(); ?>';
        sellerId  = '<?php /* @escapeNotVerified */ echo $block->getSellerId(); ?>';
        sku = '<?php /* @escapeNotVerified */ echo $block->getProduct() != null?$block->getProduct()->getSku(): null; ?>';
        productId = '<?php /* @escapeNotVerified */ echo $block->getProduct() != null?$block->getProduct()->getId(): 0; ?>';
    </script>

</div>