<?php
/**
 * Copyright © 2017 Ptaang, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Ptaang\Seller\Block\Form\NewProduct $block */
?>
<div id="new-product-form" class="new-product-form" data-bind="scope:'sellernewproduct'">
    <div class="block-manage-products add-new-products">
        <div class="form-block">
            <form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('seller/account/productPost') ?>"
                  method="post" id="form-validate" enctype="multipart/form-data"
                  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                  data-bind="submit:createProduct, blockLoader: newProduct.formLoader">
                <fieldset class="fieldset info" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                    <legend class="legend">
                        <?php /* @escapeNotVerified */ echo __("Product information"); ?>
                    </legend>
                    <div class="field field-type required">
                        <label class="label" for="type"><?php /* @escapeNotVerified */ echo __("Choose the type of Product"); ?></label>
                        <div class="control">
                            <select id="type" class="required-entry" name="attribute_set_id" data-bind="options: newProduct.productTypes,
                                                                                optionsText: 'name',
                                                                                optionsValue: 'id',
                                                                                optionsCaption: $t('Choose your type Product...'),
                                                                                value: newProduct.selectedProductType,
                                                                                event:{ change: selectProductType}"></select>
                        </div>
                    </div>
                    <div class="field field-category required">
                        <label class="label" for="category"><?php /* @escapeNotVerified */ echo __("Categories"); ?></label>
                        <div class="control">
                            <input id="category" name="custom_attributes[category]" class="input-text required-entry" type="text" readonly="readonly"
                                   data-bind="click: showCategoryList, value: newProduct.categorySelected">
                            <ul class="category-list" data-bind="foreach: { data: newProduct.categoryList, as: 'category' },
                                                                                visible: newProduct.showCategoryList">
                                <!-- ko foreach: $parent.getRegion('category') -->
                                    <!-- ko template: {name: getTemplate(), data: category} --><!-- /ko -->
                                <!-- /ko -->
                            </ul>
                        </div>
                    </div>
                    <?php echo $this->getChildHtml("form_attributes"); ?>
                </fieldset>
                <?php echo $this->getChildHtml('form_image') ?>

                <fieldset class="fieldset extra-info" data-bind="foreach: { data: newProduct.attributes, as: 'attribute' }">
                    <legend class="legend">
                        <?php /* @escapeNotVerified */ echo __("Product extra information"); ?>
                    </legend>
                    <!-- ko if: (attribute.frontend_input == 'select') -->
                        <!-- ko foreach: $parent.getRegion('attributeSelect') -->
                             <!-- ko template: {name: getTemplate(), data: attribute } --><!-- /ko -->
                         <!-- /ko -->
                    <!-- /ko -->
                </fieldset>

                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action save primary" type="submit" title="Save">
                            <span><?php /* @escapeNotVerified */ echo __("Create Product"); ?></span>
                        </button>
                    </div>
                 </div>
            </form>
        </div>
    </div>
    <script type="text/x-magento-init">
           {
               "#new-product-form": {
                   "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
               }
           }
    </script>
    <script>
        storeCode = '<?php /* @escapeNotVerified */ echo $block->getCurrentWebsiteCode(); ?>';
        token = '<?php /* @escapeNotVerified */ echo $block->getToken(); ?>';
    </script>

</div>